Update SongodaAPI.java
TheProgramSrc/SuperCoreAPI pull request #23
Opened 2022-01-28 12:55 UTC by mixeration

Hello Fran, Its me. Mixeration from Songoda Market

2022-01-31 20:52 UTC, Im-Fran requested changes
Please fix the issues and take my feedback regarding the name of the method 😃

2022-01-31 20:52 UTC, Im-Fran commented on src/main/java/xyz/theprogramsrc/supercoreapi/global/apis/songoda/SongodaAPI.java
> +    public static String rating(String pluginId){
I would change the method name to `getRating` instead of `rating`

2022-01-31 20:52 UTC, Im-Fran commented on src/main/java/xyz/theprogramsrc/supercoreapi/global/apis/songoda/SongodaAPI.java
> +        String content = utils.readWithInputStream("https://songoda.com/api/v2/products/id/" + pluginId);
This should be `Utils.readWithInputStream`, the class utils is not in lowercase

2022-01-31 20:52 UTC, Im-Fran commented on src/main/java/xyz/theprogramsrc/supercoreapi/global/apis/songoda/SongodaAPI.java
> +            return "null;
You forgot the `"` after `"null`

2022-01-31 20:53 UTC, Im-Fran commented
Also you should check the CodeQL comments in the failed check :p

2022-01-31 21:06 UTC, mixeration commented on src/main/java/xyz/theprogramsrc/supercoreapi/global/apis/songoda/SongodaAPI.java
> +            return "null;
okey, I will do it now !

2022-01-31 22:44 UTC, Im-Fran approved these changes

2022-02-20 00:56 UTC, Im-Fran commented
This will be included into the new API [TheProgramSrc/SimpleCoreAPI](https://github.com/TheProgramSrc/SimpleCoreAPI) :)

2023-09-03 21:28 UTC, closed without merging